import requests

BASE_URL = "http://127.0.0.1:8000"

token = input("Paste your Supabase access token: ").strip()

headers = {
    "Authorization": f"Bearer {token}"
}

# Profile generated by AI analyzer
PROFILE_ID = 7

# Create a new project using an already uploaded original image
data = {
    "name": "AI Generated Style Test",
    "original_image_url": "http://127.0.0.1:8000/media/uploads/original.jpg",
    "editing_profile": PROFILE_ID
}

response = requests.post(
    f"{BASE_URL}/api/projects/",
    headers=headers,
    json=data
)

print("\nPROJECT CREATION STATUS:", response.status_code)
print("PROJECT RESPONSE:")
print(response.text)

if response.status_code != 201:
    raise SystemExit("Project creation failed.")

project = response.json()
project_id = project["id"]

# Apply AI-generated style
apply_data = {
    "project_id": project_id,
    "profile_id": PROFILE_ID
}

response = requests.post(
    f"{BASE_URL}/api/apply-style/",
    headers=headers,
    json=apply_data
)

print("\nSTYLE APPLICATION STATUS:", response.status_code)
print("STYLE APPLICATION RESPONSE:")
print(response.text)