# Generated by Django 6.1.1 on 2026-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_demoprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('detailed_explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
